In [448]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
from datetime import date
from googletrans import Translator
import os
from time import sleep

In [376]:
page = requests.get('https://www.cisa.gov/known-exploited-vulnerabilities-catalog?page=0',
    headers={"User-Agent": "szkolenie_uj/1.0"},
    timeout=10
)

print("STATUS:", page.status_code)

STATUS: 200

In [377]:
soup = BeautifulSoup(page.text, 'html.parser')

In [378]:
type(soup)

bs4.BeautifulSoup

In [379]:
print(soup)

<!DOCTYPE html>

<html class="no-js" dir="ltr" lang="en" prefix="og: https://ogp.me/ns#">
<head>
<meta charset="utf-8"/>
<meta content="For the benefit of the cybersecurity community and network defenders—and to help every organization better manage vulnerabilities and keep pace with threat" name="description"/>
<link href="https://www.cisa.gov/known-exploited-vulnerabilities-catalog" rel="canonical"/>
<meta content="Cybersecurity and Infrastructure Security Agency CISA" property="og:site_name"/>
<meta content="website" property="og:type"/>
<meta content="https://www.cisa.gov/known-exploited-vulnerabilities-catalog" property="og:url"/>
<meta content="Known Exploited Vulnerabilities Catalog | CISA" property="og:title"/>
<meta content="For the benefit of the cybersecurity community and network defenders—and to help every organization better manage vulnerabilities and keep pace with threat activity—CISA maintains the authoritative source of vulnerabilities that have been exploited in the wild. Organizations should use the KEV catalog as an input to their vulnerability management prioritization framework.How to use the KEV CatalogThe KEV catalog is also available in these formats:" property="og:description"/>
<meta content="Drupal 11 (https://www.drupal.org)" name="Generator"/>
<meta content="width" name="MobileOptimized"/>
<meta content="true" name="HandheldFriendly"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="/profiles/cisad8_gov/themes/custom/gesso/favicon.png" rel="icon" type="image/png"/>
<title>Known Exploited Vulnerabilities Catalog | CISA</title>
<link href="/sites/default/files/css/css_GJVPkkHhGJbNugHB0nbdRgWMR_OgC0g1_rgFzoH3Fx0.css?delta=0&amp;language=en&amp;theme=guswds&amp;include=eJxFjmGuwyAMgy8UNUdCATLKykiVhLW9_UPTuvcnsj8rsiO7swaTVKkFW0lrLyEOd-mG5lebHtLGubpooJREc5WOP7U8VLpzzzABY9axU1voSSfw6fN9u9nXwoMSuwVj0rRGOcNRc2HHH4Ay7MiGpUmkBo0uGT5H1ZZZ0Q9JMrdy8ll_p7lakjfrhdJ55rCTUlHaV7v7_8ky-j5iq7ZyBrvM-YWRjMFFWiQNTrYZfh28Kx-Gn7u8JI_Gf4Dfe5Y" media="all" rel="stylesheet"/>
<link href="//fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&amp;family=Public+Sans:wght@400;500;600;700&amp;display=swap" media="all" rel="stylesheet"/>
<link href="/sites/default/files/css/css_cT8Wuuh0uaP57PYOg2zIn5bQEesQzWWTG4KucKolJRA.css?delta=2&amp;language=en&amp;theme=guswds&amp;include=eJxFjmGuwyAMgy8UNUdCATLKykiVhLW9_UPTuvcnsj8rsiO7swaTVKkFW0lrLyEOd-mG5lebHtLGubpooJREc5WOP7U8VLpzzzABY9axU1voSSfw6fN9u9nXwoMSuwVj0rRGOcNRc2HHH4Ay7MiGpUmkBo0uGT5H1ZZZ0Q9JMrdy8ll_p7lakjfrhdJ55rCTUlHaV7v7_8ky-j5iq7ZyBrvM-YWRjMFFWiQNTrYZfh28Kx-Gn7u8JI_Gf4Dfe5Y" media="all" rel="stylesheet"/>
<script data-drupal-selector="drupal-settings-json" type="application/json">{"path":{"baseUrl":"\/","pathPrefix":"","currentPath":"node\/20326","currentPathIsAdmin":false,"isFront":false,"currentLanguage":"en","currentQuery":{"page":"0"}},"pluralDelimiter":"\u0003","suppressDeprecationErrors":true,"gtag":{"tagId":"","consentMode":false,"otherIds":[],"events":[],"additionalConfigInfo":[]},"ajaxPageState":{"libraries":"eJx1kFGOwyAMRC9Ew5GQMQ5hQ3Bkm6a5_aK26UqV9sdiZp5kM5HMSIIyFqhBF5DScojdjJt6tbMO7XClVIwlACJLKtz85zXNws2oJUcPG_Tqk_Qd6vSWbgYk08t9qQkXwjXy43aUlMkuSHm2Wy1buZygBILLIMOL9B_DZeZcKRhkn8f41hP8wBe0udz1SOqjECSUvsXLea4LsTKul5UrR6iXMgIlcRVO7gPspSYSbwcjj-IIbXRxpako8p3k9Nxo5G4HgSywL58e_pypt73HWnSh5PRUo83HscsZc40g43Zdx_6Xcl1nSpnv4f0zaFBPK6j-32TC1Ny90KH-OaeNU6_0C-yOyGc","theme":"guswds","theme_token":null},"ajaxTrustedUrl":{"\/known-exploited-vulnerabilities-catalog":true},"gtm":{"tagId":null,"settings":{"data_layer":"dataLayer","include_classes":false,"allowlist_classes":"","blocklist_classes":"","include_environment":false,"environment_id":"","environment_token":""},"tagIds":["GTM-53QLXSL9"]},"data":{"extlink":{"extTarget":false,"extTargetAppendNewWindowDisplay":true,"extTargetAppendNewWindowLabel":"(opens in a new window)","extTargetNoOverride":false,"extNofollow":false,"extTitleNoOverride":false,"extNoreferrer":false,"extFollowNoOverride":false,"extClass":"ext","extLabel":"(link is external)","extImgClass":false,"extSubdomains":true,"extExclude":"(.\\.gov$)|(.\\.mil$)|(.\\.mil\/)|(.\\.gov\/)","extInclude":"","extCssExclude":".c-menu--social,.c-menu--footer,.c-social-links,.c-text-cta--button,.usa-footer__contact-info","extCssInclude":"","extCssExplicit":"","extAlert":true,"extAlertText":"You are now leaving an official website of the United State Government (USG), the Department of Homeland Security (DHS) and the Cybersecurity and Infrastructure Security Agency (CISA). Links to non-USG, non-DHS and non-CISA sites are provided for the visitor\u0027s convenience and do not represent an endorsement by USG, DHS or CISA of any commercial or private issues, products or services. Note that the privacy policy of the linked site may differ from that of USG, DHS and CISA.","extHideIcons":false,"mailtoClass":"mailto","telClass":"","mailtoLabel":"(link sends email)","telLabel":"(link is a phone number)","extUseFontAwesome":false,"extIconPlacement":"append","extPreventOrphan":false,"extFaLinkClasses":"fa fa-external-link","extFaMailtoClasses":"fa fa-envelope-o","extAdditionalLinkClasses":"","extAdditionalMailtoClasses":"","extAdditionalTelClasses":"","extFaTelClasses":"fa fa-phone","allowedDomains":[],"extExcludeNoreferrer":""}},"ckeditorAccordion":{"accordionStyle":{"collapseAll":1,"keepRowsOpen":0,"animateAccordionOpenAndClose":1,"openTabsWithHash":1,"allowHtmlInTitles":0}},"facets":{"softLimit":{"vendor_project":15},"softLimitSettings":{"vendor_project":{"showLessLabel":"Show less","showMoreLabel":"Show more"}}},"user":{"uid":0,"permissionsHash":"0f75d40308887aebba0d5b0d2671305b73c9431902f86e672380a6dc6ab97d07"}}</script>
<script src="/sites/default/files/js/js_-cGpsIm_y3dXA0WNo-iJLB92YJ9m-1MpsVlQOxQ8o4A.js?scope=header&amp;delta=0&amp;language=en&amp;theme=guswds&amp;include=eJx1jVEOgyAMQC-EcCRS2opMpAvU6W6_ZYofJvtpeI-XFmempFI9IEqlJMVdLztWKcqFDO-aU5kd1fUJ2Z5oRkDW1u1BFifGOcg-bIkia4-ajDrktKRufGOoOH1Lf5TuEiaKxMxeIbr4HXe28IBbtJi4to2aC5WBsK5L6OZ3zocsOHcVswTInZShcTVrG5mivPy5GArktyZs7u-PRSofS0x-Dg"></script>
<script src="/modules/contrib/google_tag/js/gtag.js?te690y"></script>
<script src="/modules/contrib/google_tag/js/gtm.js?te690y"></script>
<script async="" id="_fed_an_ua_tag" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=DHS&amp;subagency=CISA&amp;siteplatform=Drupal&amp;yt=true"></script>
</head>
<body class="path-node not-front node-page node-page--node-type-flexible-page" id="top">
<div class="c-skiplinks">
<a class="c-skiplinks__link u-visually-hidden u-focusable" href="#main">Skip to main content</a>
</div>
<noscript><iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-53QLXSL9" style="display:none;visibility:hidden" width="0"></iframe></noscript>
<div class="dialog-off-canvas-main-canvas" data-off-canvas-main-canvas="">
<div class="l-site-container">
<section aria-label="Official government website" class="usa-banner">
<div class="usa-accordion"> <header class="usa-banner__header">
<div class="usa-banner__inner">
<div class="grid-col-auto">
<img alt="U.S. flag" class="usa-banner__header-flag" src="/profiles/cisad8_gov/themes/custom/gesso/dist/images/us_flag_small.png"/>
</div>
<div class="grid-col-fill tablet:grid-col-auto">
<p class="usa-banner__header-text">An official website of the United States government</p>
<p aria-hidden="true" class="usa-banner__header-action">Here’s how you know</p></div>
<button aria-controls="gov-banner" aria-expanded="false" class="usa-accordion__button usa-banner__button">
<span class="usa-banner__button-text">Here’s how you know</span>
</button>
</div>
</header>
<div class="usa-banner__content usa-accordion__content" id="gov-banner">
<div class="grid-row grid-gap-lg">
<div class="usa-banner__guidance tablet:grid-col-6">
<img alt="Dot gov" class="usa-banner__icon usa-media-block__img" src="/profiles/cisad8_gov/themes/custom/gesso/dist/images/icon-dot-gov.svg"/>
<div class="usa-media-block__body">
<p>
<strong>Official websites use .gov</strong>
<br/> A <strong>.gov</strong> website belongs to an official government organization in the United States.
              </p>
</div>
</div>
<div class="usa-banner__guidance tablet:grid-col-6">
<img alt="HTTPS" class="usa-banner__icon usa-media-block__img" src="/profiles/cisad8_gov/themes/custom/gesso/dist/images/icon-https.svg"/>
<div class="usa-media-block__body">
<p>
<strong>Secure .gov websites use HTTPS</strong>
<br/> A <strong>lock</strong> (<span class="icon-lock"><svg aria-labelledby="banner-lock-title banner-lock-description" class="usa-banner__lock-image" height="64" role="img" viewbox="0 0 52 64" width="52" xmlns="http://www.w3.org/2000/svg"><title id="banner-lock-title">Lock</title><desc id="banner-lock-description">A locked padlock</desc><path d="M26 0c10.493 0 19 8.507 19 19v9h3a4 4 0 0 1 4 4v28a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V32a4 4 0 0 1 4-4h3v-9C7 8.507 15.507 0 26 0zm0 8c-5.979 0-10.843 4.77-10.996 10.712L15 19v9h22v-9c0-6.075-4.925-11-11-11z" fill="#000000" fill-rule="evenodd"></path></svg></span>) or <strong>https://</strong> means you’ve safely connected to the .gov website. Share sensitive information only on official, secure websites.
              </p>
</div>
</div>
</div>
</div>
</div>
</section>
<div class="c-block c-global-header-btns c-global-btns">
<div class="l-constrain l-constrain">
<div class="c-block__content">
<div class="c-block c-block--provider-block-content c-block--id-block-content83069f9f-34fc-4d54-86ec-936a204f8088" id="block-globalbuttons">
<div class="c-block__content">
<div class="c-field c-field--name-body c-field--type-text-with-summary c-field--label-hidden">
<div class="c-field__content"><p><span><strong>Due to the lapse in federal funding, this website will not be actively managed.  </strong></span><a href="https://go.dhs.gov/lapse-2026"><span><strong>Read More</strong></span></a></p><p><a class="c-button c-button--basic c-button--blue" href="/resources-tools/resources/free-cybersecurity-services-and-tools" title="Free Cyber Services">no-cost Cyber Services</a><a class="c-button c-button--basic c-button--green60" href="/securebydesign">Secure by design </a><a class="c-button c-button--basic c-button--teal" href="/secureyourbusiness">Secure Your Business</a><a class="c-button c-button--campaign" href="/node/8056">Shields Up</a><a class="c-button c-button--report" href="/report">Report A Cyber Issue</a> </p></div></div>
</div>
</div>
</div>
</div>
</div>
<div class="usa-overlay"></div>
<header class="usa-header usa-header--extended" role="banner">
<div class="usa-navbar">
<div class="l-constrain">
<div class="usa-navbar__row">
<div class="c-block c-site-header">
<div class="l-constrain">
<div class="c-block__content">
<div class="c-block c-block--provider-block-content c-block--id-block-contentbc4e6844-86b4-4e20-b163-a73bda3d1d76" id="block-guswds-cisaheaderblock">
<div class="c-block__content">
<div class="c-field c-field--name-body c-field--type-text-with-summary c-field--label-hidden">
<div class="c-field__content"><a href="/"><img alt="Cybersecurity &amp; Infrastructure Security Agency logo America’s Cyber Security Defense Agency National Coordinator For Critical Infrastructure Security and Resilience" src="/sites/default/files/images/SVG/header_logo_tagline_update.svg"><img alt="Cybersecurity &amp; Infrastructure Security Agency logo America’s Cyber Security Defense Agency National Coordinator For Critical Infrastructure Security and Resilience" class="print-only" src="/sites/default/files/images/SVG/header_logo_tagline_update.png"/></img></a></div></div>
</div>
</div>
</div>
</div>
</div>
<div class="c-block c-site-header-mobile">
<div class="l-constrain">
<div class="c-block__content">
<div class="c-block c-block--provider-block-content c-block--id-block-content283396c9-cd36-4ce3-b1e2-9b5576ab4f50" id="block-guswds-cisaheaderblockmobile">
<div class="c-block__content">
<div class="c-field c-field--name-body c-field--type-text-with-summary c-field--label-hidden">
<div class="c-field__content"><a href="/"><img alt="CISA Logo" src="/sites/default/files/images/SVG/mobile_logo_wordmark.svg"/></a></div></div>
</div>
</div>
</div>
</div>
</div>
<div class="usa-navbar__search">
<div class="usa-navbar__search-header">
<p>Search</p>
</div>
<div class="usa-search">
<script async="" src="https://cse.google.com/cse.js?cx=ffc4c79e29d5b3a8c"></script>
<div class="gcse-searchbox-only" data-resultsurl="/search"> </div>
</div>
</div>
<button class="mobile-menu-button usa-menu-btn">Menu</button>
</div>
</div>
</div>
<div class="c-block c-tagline-mobile">
<div class="l-constrain">
<div class="c-block__content">
<div class="c-block c-block--provider-block-content c-block--id-block-contentc8d12e9d-7e48-4708-90c1-563609c4b566" id="block-guswds-mobiletaglinecontainer">
<div class="c-block__content">
<div class="c-field c-field--name-body c-field--type-text-with-summary c-field--label-hidden">
<div class="c-field__content"><p><center><img alt="America's Cyber Defense Agency" src="/sites/default/files/images/SVG/header_tagline_mobile_update.svg"/></center></p></div></div>
</div>
</div>
</div>
</div>
</div>
<nav aria-label="Primary navigation" class="usa-nav" role="navigation">
<div class="usa-nav__inner l-constrain">
<div class="usa-nav__row">
<button class="usa-nav__close">Close</button>
<div class="usa-search">
<script async="" src="https://cse.google.com/cse.js?cx=ffc4c79e29d5b3a8c"></script>
<div class="gcse-searchbox-only" data-resultsurl="/search"> </div>
</div>
<ul class="usa-nav__primary usa-accordion">
<li class="usa-nav__primary-item topics">
<button aria-controls="basic-mega-nav-section-1" aria-expanded="false" class="usa-accordion__button usa-nav__link">
<span>Topics</span>
</button>
<div class="usa-nav__submenu usa-megamenu" hidden="" id="basic-mega-nav-section-1">
<div class="usa-megamenu__parent-link">
<a href="/topics">Topics</a>
</div>
<div class="usa-megamenu__menu-items">
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/topics/cybersecurity-best-practices">
<span>Cybersecurity Best Practices</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/topics/cyber-threats-and-response">
<span>Cyber Threats and Response</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/topics/critical-infrastructure-security-and-resilience">
<span>Critical Infrastructure Security and Resilience</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/topics/election-security">
<span>Election Security</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/topics/emergency-communications">
<span>Emergency Communications</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/topics/industrial-control-systems">
<span>Industrial Control Systems</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/topics/information-communications-technology-supply-chain-security">
<span>Information and Communications Technology Supply Chain Security</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/topics/partnerships-and-collaboration">
<span>Partnerships and Collaboration</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/topics/physical-security">
<span>Physical Security</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/topics/risk-management">
<span>Risk Management</span>
</a>
</div>
</div>
</div>
<div class="c-menu-feature-links">
<div class="c-menu-feature-links__title">
<a href="/audiences">        How can we help?
      </a> </div>
<div class="c-menu-feature-links__content"><a href="/topics/government">Government</a><a href="/topics/educational-institutions">Educational Institutions</a><a href="/topics/industry">Industry</a><a href="/topics/state-local-tribal-and-territorial">State, Local, Tribal, and Territorial</a><a href="/topics/individuals-and-families">Individuals and Families</a><a href="/topics/small-and-medium-businesses">Small and Medium Businesses</a><a href="/audiences/find-help-locally">Find Help Locally</a><a href="/audiences/faith-based-community">Faith-Based Community</a><a href="/audiences/executives">Executives</a><a href="/audiences/high-risk-communities">High-Risk Communities</a></div>
</div>
</div>
</li>
<li class="usa-nav__primary-item spotlight">
<a class="usa-nav__link" href="/spotlight">
<span>Spotlight</span>
</a>
</li>
<li class="usa-nav__primary-item resources--tools">
<button aria-controls="basic-mega-nav-section-3" aria-expanded="false" class="usa-accordion__button usa-nav__link">
<span>Resources &amp; Tools</span>
</button>
<div class="usa-nav__submenu usa-megamenu" hidden="" id="basic-mega-nav-section-3">
<div class="usa-megamenu__parent-link">
<a href="/resources-tools">Resources &amp; Tools</a>
</div>
<div class="usa-megamenu__menu-items">
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/resources-tools/all-resources-tools">
<span>All Resources &amp; Tools</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/resources-tools/services">
<span>Services</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/resources-tools/programs">
<span>Programs</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/resources-tools/resources">
<span>Resources</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/resources-tools/training">
<span>Training</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/resources-tools/groups">
<span>Groups</span>
</a>
</div>
</div>
</div>
</div>
</li>
<li class="usa-nav__primary-item news--events">
<button aria-controls="basic-mega-nav-section-4" aria-expanded="false" class="usa-accordion__button usa-nav__link">
<span>News &amp; Events</span>
</button>
<div class="usa-nav__submenu usa-megamenu" hidden="" id="basic-mega-nav-section-4">
<div class="usa-megamenu__parent-link">
<a href="/news-events">News &amp; Events</a>
</div>
<div class="usa-megamenu__menu-items">
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/news-events/directives">
<span>Directives</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/news-events/news">
<span>News</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/news-events/events">
<span>Events</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/news-events/cybersecurity-advisories">
<span>Cybersecurity Alerts &amp; Advisories</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/news-events/request-speaker">
<span>Request a CISA Speaker</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/news-events/congressional-testimony">
<span>Congressional Testimony</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/cisa-conferences">
<span>CISA Conferences</span>
</a>
</div>
</div>
<div class="usa-col">
<div class="usa-nav__submenu-item">
<a href="/cisa-live">
<span>CISA Live!</span>
</a>
</div>
</div>
</div>
</div>
</li>
<li class="usa-nav__primary-item careers">
<button aria-controls="basic-mega-nav-section-5" aria-expanded="false" class="usa-accordion__button usa-nav__link">
<span>Careers</span>
</button>
<div class="usa-nav__submenu usa-megamenu" hidden="" id="basic-mega-nav-section-5">
<div class="usa-megamenu__parent-link">
<a href="/careers">Careers</a>
</div>
<div class="usa-megamenu__menu-items">
<div class="usa-col">
<div class="usa-nav__submenu-item">

In [380]:
meta = soup.find_all(class_="c-teaser__meta")

In [381]:
teaser__meta_list = []

for n in meta:
    teaser__meta_list.append(n.text)

print(teaser__meta_list)

['Microsoft | Windows', 'ConnectWise | ScreenConnect', 'SimpleHelp  | SimpleHelp', 'SimpleHelp  | SimpleHelp', 'Samsung | MagicINFO 9 Server', 'D-Link | DIR-823X', 'Marimo | Marimo', 'Microsoft | Defender', 'JetBrains | TeamCity', 'Quest | KACE Systems Management Appliance (SMA)', 'Cisco | Catalyst SD-WAN Manager', 'Synacor | Zimbra Collaboration Suite (ZCS)', 'PaperCut | NG/MF', 'Kentico | Kentico Xperience', 'Cisco | Catalyst SD-WAN Manager', 'Cisco | Catalyst SD-WAN Manger', 'Apache | ActiveMQ', 'Microsoft | SharePoint Server', 'Microsoft | Office', 'Adobe | Acrobat and Reader']

In [382]:
results[0].text

'SimpleHelp Missing Authorization Vulnerability:         SimpleHelp contains a missing authorization vulnerability that could allow low-privileged technicians to create API keys with excessive permissions. These API keys can be used to escalate privileges to the server admin role.\n        \n'

In [383]:
title = soup.find_all(class_="c-teaser__title")

In [384]:
teaser__title_list = []
for n in title:
    teaser__title_list.append(n.find("span").text)

In [385]:
name = soup.find_all(class_="c-teaser__vuln-name")

In [386]:
print(len(name))
print(name[0])

20
<div class="c-teaser__vuln-name">Microsoft Windows Protection Mechanism Failure Vulnerability: <span>        Microsoft Windows Shell contains a protection mechanism failure vulnerability that allows an unauthorized attacker to perform spoofing over a network.
        </span>
</div>

In [387]:
teaser__vuln_name = []
teaser__vuln_name_value = []

for n in name:
    teaser__vuln_name.append(n.find(string=True, recursive=False).strip())
    teaser__vuln_name_value.append(n.find("span").text.strip())

In [388]:
print(titles)
print(descriptions)

['SimpleHelp Missing Authorization Vulnerability:', 'SimpleHelp Path Traversal Vulnerability:', 'Samsung MagicINFO 9 Server Path Traversal Vulnerability:', 'D-Link DIR-823X Command Injection Vulnerability:', 'Marimo Remote Code Execution Vulnerability:', 'Microsoft Defender Insufficient Granularity of Access Control Vulnerability:', 'JetBrains TeamCity Relative Path Traversal Vulnerability:', 'Quest KACE Systems Management Appliance (SMA) Improper Authentication Vulnerability:', 'Cisco Catalyst SD-WAN Manager Storing Passwords in a Recoverable Format Vulnerability:', 'Synacor Zimbra Collaboration Suite (ZCS) Cross-site Scripting Vulnerability:', 'PaperCut NG/MF Improper Authentication Vulnerability:', 'Kentico Xperience Path Traversal Vulnerability:', 'Cisco Catalyst SD-WAN Manager Exposure of Sensitive Information to an Unauthorized Actor Vulnerability:', 'Cisco Catalyst SD-WAN Manager Incorrect Use of Privileged APIs Vulnerability:', 'Apache ActiveMQ Improper Input Validation Vulnerability:', 'Microsoft SharePoint Server Improper Input Validation Vulnerability:', 'Microsoft Office Remote Code Execution:', 'Adobe Acrobat and Reader Prototype Pollution Vulnerability:', 'Fortinet FortiClient EMS SQL Injection Vulnerability:', 'Adobe Acrobat Use-After-Free Vulnerability:']
['SimpleHelp contains a missing authorization vulnerability that could allow low-privileged technicians to create API keys with excessive permissions. These API keys can be used to escalate privileges to the server admin role.', 'SimpleHelp contains a path traversal vulnerability that allows admin users to upload arbitrary files anywhere on the file system by uploading a crafted zip file (i.e. zip slip). This can be exploited to execute arbitrary code on the host in the context of the SimpleHelp server user.', 'Samsung MagicINFO 9 Server contains a path traversal vulnerability that could allow an attacker to write arbitrary files as system authority.', 'D-Link DIR-823X contains a command injection vulnerability that allows an authorized attacker to execute arbitrary commands on remote devices by sending a POST request to /goform/set_prohibiting via the corresponding function. The impacted product could be end-of-life (EoL) and/or end-of-service (EoS). Users should discontinue product utilization.', 'Marimo contains an pre-authorization remote code execution vulnerability, allowing an unauthenticated attacked to shell access and execute arbitrary system commands.', 'Microsoft Defender contains an insufficient granularity of access control vulnerability that could allow an authorized attacker to escalate privileges locally.', 'JetBrains TeamCity contains a relative path traversal vulnerability that could allow limited admin actions to be performed.', 'Quest KACE Systems Management Appliance (SMA) contains an improper authentication vulnerability that could allow attackers to impersonate legitimate users without valid credentials.', 'Cisco Catalyst SD-WAN Manager contains a storing passwords in a recoverable format vulnerability that allows an authenticated, local attacker to gain DCA user privileges by accessing a credential file for the DCA user on the filesystem as a low-privileged user.', "Synacor Zimbra Collaboration Suite (ZCS) contains a cross-site scripting vulnerability that could allow attackers to execute arbitrary JavaScript within the user's session, potentially leading to unauthorized access to sensitive information.", 'PaperCut NG/MF contains an improper authentication vulnerability that could allow remote attackers to bypass authentication on affected installations via the SecurityRequestFilter class.', "Kentico Xperience contains a path traversal vulnerability that could allow an authenticated user's Staging Sync Server to upload arbitrary data to path relative locations.", 'Cisco Catalyst SD-WAN Manager contains an exposure of sensitive information to an unauthorized actor vulnerability that could allow remote attackers to view sensitive information on affected systems.', 'Cisco Catalyst SD-WAN Manager contains an incorrect use of privileged APIs vulnerability due to improper file handling on the API interface of an affected system. An attacker could exploit this vulnerability by uploading a malicious file on the local file system. A successful exploit could allow the attacker to overwrite arbitrary files on the affected system and gain vmanage user privileges.', 'Apache ActiveMQ contains an improper input validation vulnerability that allows for code injection.', 'Microsoft SharePoint Server contains an improper input validation vulnerability that allows an unauthorized attacker to perform spoofing over a network.', 'Microsoft Office Excel contains a remote code execution vulnerability that could allow an attacker to take complete control of an affected system if a user opens a specially crafted Excel file that includes a malformed object.', 'Adobe Acrobat and Reader contain a prototype pollution vulnerability that allows for arbitrary code execution.', 'Fortinet FortiClient EMS contains a SQL injection vulnerability that may allow an unauthenticated attacker to execute unauthorized code or commands via specifically crafted HTTP requests.', 'Adobe Acrobat contains a use-after-free vulnerability that allows for code execution']

In [389]:
teaser__cwes_line = soup.find_all(class_='c-teaser__cwes-line')

In [390]:
len(teaser__cwes_line)
teaser__cwes_line[0]

<div class="c-teaser__cwes-line">
<p>Related CWE:
                          <a class="c-teaser__cwe" href="https://cwe.mitre.org/data/definitions/693">CWE-693</a>
</p>
</div>

In [391]:
realted_cwe_link = []
related_cwe = []

for n in teaser__cwes_line:
    realted_cwe_link.append(n.find('a')['href'])
    related_cwe.append(n.find("a").text)

In [392]:
realted_cwe_link[1]
related_cwe[1]

'CWE-22'

In [393]:
content = soup.find_all(class_='c-teaser__content')

In [394]:
content[0]

<div class="c-teaser__content">
<div class="c-teaser__eyebrow">
<div class="c-teaser__meta">Microsoft | Windows</div>
</div>
<h3 class="c-teaser__title">
<a href="https://www.cve.org/CVERecord?id=CVE-2026-32202" target="_self">
<span>CVE-2026-32202</span>
</a> </h3>
<div class="c-teaser__vuln-name">Microsoft Windows Protection Mechanism Failure Vulnerability: <span>        Microsoft Windows Shell contains a protection mechanism failure vulnerability that allows an unauthorized attacker to perform spoofing over a network.
        </span>
</div>
<div class="c-teaser__cwes-block">
<div class="c-teaser__cwes-line">
<p>Related CWE:
                          <a class="c-teaser__cwe" href="https://cwe.mitre.org/data/definitions/693">CWE-693</a>
</p>
</div>
</div>
<p>Known To Be Used in Ransomware Campaigns? <strong>Unknown</strong></p>
<div class="c-teaser__teaser-info">
<div class="c-teaser__teaser-action">
<span class="c-teaser__kev-label">Action:</span> Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.
          </div>
<div class="c-teaser__teaser-dates">
<ul>
<li><span class="c-teaser__kev-label">Date Added:</span> 2026-04-28</li>
<li><span class="c-teaser__kev-label">Due Date:</span> 2026-05-12</li>
</ul>
</div>
</div>
<div class="c-teaser__notes-title">Additional Notes</div>
<div class="c-teaser__notes-content hide">
<div class="c-teaser__notes"><a href="https://msrc.microsoft.com/update-guide/en-US/vulnerability/CVE-2026-32202">https://msrc.microsoft.com/update-guide/en-US/vulnerability/CVE-2026-32202</a> ; <a href="https://nvd.nist.gov/vuln/detail/CVE-2026-32202">https://nvd.nist.gov/vuln/detail/CVE-2026-32202</a></div> </div>
</div>

In [395]:
p = content[0].find_all('p')

In [396]:
p[1].text

'Known To Be Used in Ransomware Campaigns? Unknown'

In [397]:
p[1].find("strong").text

'Unknown'

In [398]:
ransomware_campaigns = []

for n in content:
    p = n.find_all("p")
    ransomware_campaigns.append(p[1].find("strong").text)

In [399]:
ransomware_campaigns[0]

'Unknown'

In [400]:
actions = soup.find_all(class_='c-teaser__teaser-action')

In [401]:
actions[0]

<div class="c-teaser__teaser-action">
<span class="c-teaser__kev-label">Action:</span> Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.
          </div>

In [402]:
actions[0].find("span").next_sibling.strip()

'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.'

In [403]:
action_list = []

for n in actions:
    action_list.append(n.find("span").next_sibling.strip())

In [404]:
action_list[0]

'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.'

In [405]:
date = soup.find_all(class_='c-teaser__teaser-dates')

In [406]:
date[0]

<div class="c-teaser__teaser-dates">
<ul>
<li><span class="c-teaser__kev-label">Date Added:</span> 2026-04-28</li>
<li><span class="c-teaser__kev-label">Due Date:</span> 2026-05-12</li>
</ul>
</div>

In [407]:
date[0].find('span').next_sibling

' 2026-04-28'

In [408]:
Due_date = date[0].find_all("li")
Due_date[1].find("span").next_sibling.strip()

'2026-05-12'

In [409]:
Added_date_list = []
Due_date_list = []

for n in date:
    li = n.find_all("li")
    Added_date_list.append(li[0].find("span").next_sibling.strip())
    Due_date_list.append(li[1].find("span").next_sibling.strip())

In [410]:
Added_date_list[0]

'2026-04-28'

In [411]:
Due_date_list[0]

'2026-05-12'

In [412]:
vurnelabilities=[]
vurnelabilities.append([teaser__meta_list,teaser__title_list,teaser__vuln_name, teaser__vuln_name_value,realted_cwe_link, related_cwe, ransomware_campaigns, action_list,Added_date_list, Due_date_list ])

In [413]:
vurnelabilities

[[['Microsoft | Windows',
   'ConnectWise | ScreenConnect',
   'SimpleHelp  | SimpleHelp',
   'SimpleHelp  | SimpleHelp',
   'Samsung | MagicINFO 9 Server',
   'D-Link | DIR-823X',
   'Marimo | Marimo',
   'Microsoft | Defender',
   'JetBrains | TeamCity',
   'Quest | KACE Systems Management Appliance (SMA)',
   'Cisco | Catalyst SD-WAN Manager',
   'Synacor | Zimbra Collaboration Suite (ZCS)',
   'PaperCut | NG/MF',
   'Kentico | Kentico Xperience',
   'Cisco | Catalyst SD-WAN Manager',
   'Cisco | Catalyst SD-WAN Manger',
   'Apache | ActiveMQ',
   'Microsoft | SharePoint Server',
   'Microsoft | Office',
   'Adobe | Acrobat and Reader'],
  ['CVE-2026-32202',
   'CVE-2024-1708',
   'CVE-2024-57726',
   'CVE-2024-57728',
   'CVE-2024-7399',
   'CVE-2025-29635',
   'CVE-2026-39987',
   'CVE-2026-33825',
   'CVE-2024-27199',
   'CVE-2025-32975',
   'CVE-2026-20128',
   'CVE-2025-48700',
   'CVE-2023-27351',
   'CVE-2025-2749',
   'CVE-2026-20133',
   'CVE-2026-20122',
   'CVE-2026-34197',
   'CVE-2026-32201',
   'CVE-2009-0238',
   'CVE-2026-34621'],
  ['Microsoft Windows Protection Mechanism Failure Vulnerability:',
   'ConnectWise ScreenConnect Path Traversal Vulnerability:',
   'SimpleHelp Missing Authorization Vulnerability:',
   'SimpleHelp Path Traversal Vulnerability:',
   'Samsung MagicINFO 9 Server Path Traversal Vulnerability:',
   'D-Link DIR-823X Command Injection Vulnerability:',
   'Marimo Remote Code Execution Vulnerability:',
   'Microsoft Defender Insufficient Granularity of Access Control Vulnerability:',
   'JetBrains TeamCity Relative Path Traversal Vulnerability:',
   'Quest KACE Systems Management Appliance (SMA) Improper Authentication Vulnerability:',
   'Cisco Catalyst SD-WAN Manager Storing Passwords in a Recoverable Format Vulnerability:',
   'Synacor Zimbra Collaboration Suite (ZCS) Cross-site Scripting Vulnerability:',
   'PaperCut NG/MF Improper Authentication Vulnerability:',
   'Kentico Xperience Path Traversal Vulnerability:',
   'Cisco Catalyst SD-WAN Manager Exposure of Sensitive Information to an Unauthorized Actor Vulnerability:',
   'Cisco Catalyst SD-WAN Manager Incorrect Use of Privileged APIs Vulnerability:',
   'Apache ActiveMQ Improper Input Validation Vulnerability:',
   'Microsoft SharePoint Server Improper Input Validation Vulnerability:',
   'Microsoft Office Remote Code Execution:',
   'Adobe Acrobat and Reader Prototype Pollution Vulnerability:'],
  ['Microsoft Windows Shell contains a protection mechanism failure vulnerability that allows an unauthorized attacker to perform spoofing over a network.',
   'ConnectWise ScreenConnect contains a path traversal vulnerability which could allow an attacker to execute remote code or directly impact confidential data and critical systems.',
   'SimpleHelp contains a missing authorization vulnerability that could allow low-privileged technicians to create API keys with excessive permissions. These API keys can be used to escalate privileges to the server admin role.',
   'SimpleHelp contains a path traversal vulnerability that allows admin users to upload arbitrary files anywhere on the file system by uploading a crafted zip file (i.e. zip slip). This can be exploited to execute arbitrary code on the host in the context of the SimpleHelp server user.',
   'Samsung MagicINFO 9 Server contains a path traversal vulnerability that could allow an attacker to write arbitrary files as system authority.',
   'D-Link DIR-823X contains a command injection vulnerability that allows an authorized attacker to execute arbitrary commands on remote devices by sending a POST request to /goform/set_prohibiting via the corresponding function. The impacted product could be end-of-life (EoL) and/or end-of-service (EoS). Users should discontinue product utilization.',
   'Marimo contains an pre-authorization remote code execution vulnerability, allowing an unauthenticated attacked to shell access and execute arbitrary system commands.',
   'Microsoft Defender contains an insufficient granularity of access control vulnerability that could allow an authorized attacker to escalate privileges locally.',
   'JetBrains TeamCity contains a relative path traversal vulnerability that could allow limited admin actions to be performed.',
   'Quest KACE Systems Management Appliance (SMA) contains an improper authentication vulnerability that could allow attackers to impersonate legitimate users without valid credentials.',
   'Cisco Catalyst SD-WAN Manager contains a storing passwords in a recoverable format vulnerability that allows an authenticated, local attacker to gain DCA user privileges by accessing a credential file for the DCA user on the filesystem as a low-privileged user.',
   "Synacor Zimbra Collaboration Suite (ZCS) contains a cross-site scripting vulnerability that could allow attackers to execute arbitrary JavaScript within the user's session, potentially leading to unauthorized access to sensitive information.",
   'PaperCut NG/MF contains an improper authentication vulnerability that could allow remote attackers to bypass authentication on affected installations via the SecurityRequestFilter class.',
   "Kentico Xperience contains a path traversal vulnerability that could allow an authenticated user's Staging Sync Server to upload arbitrary data to path relative locations.",
   'Cisco Catalyst SD-WAN Manager contains an exposure of sensitive information to an unauthorized actor vulnerability that could allow remote attackers to view sensitive information on affected systems.',
   'Cisco Catalyst SD-WAN Manager contains an incorrect use of privileged APIs vulnerability due to improper file handling on the API interface of an affected system. An attacker could exploit this vulnerability by uploading a malicious file on the local file system. A successful exploit could allow the attacker to overwrite arbitrary files on the affected system and gain vmanage user privileges.',
   'Apache ActiveMQ contains an improper input validation vulnerability that allows for code injection.',
   'Microsoft SharePoint Server contains an improper input validation vulnerability that allows an unauthorized attacker to perform spoofing over a network.',
   'Microsoft Office Excel contains a remote code execution vulnerability that could allow an attacker to take complete control of an affected system if a user opens a specially crafted Excel file that includes a malformed object.',
   'Adobe Acrobat and Reader contain a prototype pollution vulnerability that allows for arbitrary code execution.'],
  ['https://cwe.mitre.org/data/definitions/693',
   'https://cwe.mitre.org/data/definitions/22',
   'https://cwe.mitre.org/data/definitions/862',
   'https://cwe.mitre.org/data/definitions/22',
   'https://cwe.mitre.org/data/definitions/22',
   'https://cwe.mitre.org/data/definitions/77',
   'https://cwe.mitre.org/data/definitions/306',
   'https://cwe.mitre.org/data/definitions/1220',
   'https://cwe.mitre.org/data/definitions/23',
   'https://cwe.mitre.org/data/definitions/287',
   'https://cwe.mitre.org/data/definitions/257',
   'https://cwe.mitre.org/data/definitions/79',
   'https://cwe.mitre.org/data/definitions/287',
   'https://cwe.mitre.org/data/definitions/22',
   'https://cwe.mitre.org/data/definitions/200',
   'https://cwe.mitre.org/data/definitions/648',
   'https://cwe.mitre.org/data/definitions/20',
   'https://cwe.mitre.org/data/definitions/20',
   'https://cwe.mitre.org/data/definitions/94',
   'https://cwe.mitre.org/data/definitions/1321'],
  ['CWE-693',
   'CWE-22',
   'CWE-862',
   'CWE-22',
   'CWE-22',
   'CWE-77',
   'CWE-306',
   'CWE-1220',
   'CWE-23',
   'CWE-287',
   'CWE-257',
   'CWE-79',
   'CWE-287',
   'CWE-22',
   'CWE-200',
   'CWE-648',
   'CWE-20',
   'CWE-20',
   'CWE-94',
   'CWE-1321'],
  ['Unknown',
   'Unknown',
   'Unknown',
   'Unknown',
   'Unknown',
   'Unknown',
   'Unknown',
   'Unknown',
   'Known',
   'Unknown',
   'Unknown',
   'Unknown',
   'Known',
   'Unknown',
   'Unknown',
   'Unknown',
   'Unknown',
   'Unknown',
   'Unknown',
   'Unknown'],
  ['Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.',
   'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.',
   'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.',
   'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.',
   'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.',
   'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.',
   'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.',
   'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.',
   'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.',
   'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.',
   'Please adhere to CISA’s guidelines to assess exposure and mitigate risks associated with Cisco SD-WAN devices as outlines in CISA’s Emergency Directive 26-03 (URL listed below in Notes) and CISA’s “Hunt & Hardening Guidance for Cisco SD-WAN Devices (URL listed below in Notes). Adhere to the applicable BOD 22-01 guidance for cloud services or discontinue use of the product if mitigations are not available.',
   'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.',
   'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.',
   'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.',
   'Please adhere to CISA’s guidelines to assess exposure and mitigate risks associated with Cisco SD-WAN devices as outlines in CISA’s Emergency Directive 26-03 (URL listed below in Notes) and CISA’s “Hunt & Hardening Guidance for Cisco SD-WAN Devices (URL listed below in Notes). Adhere to the applicable BOD 22-01 guidance for cloud services or discontinue use of the product if mitigations are not available.',
   'Please adhere to CISA’s guidelines to assess exposure and mitigate risks associated with Cisco SD-WAN devices as outlines in CISA’s Emergency Directive 26-03 (URL listed below in Notes) and CISA’s “Hunt & Hardening Guidance for Cisco SD-WAN Devices (URL listed below in Notes). Adhere to the applicable BOD 22-01 guidance for cloud services or discontinue use of the product if mitigations are not available.',
   'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.',
   'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.',
   'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.',
   'Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.'],
  ['2026-04-28',
   '2026-04-28',
   '2026-04-24',
   '2026-04-24',
   '2026-04-24',
   '2026-04-24',
   '2026-04-23',
   '2026-04-22',
   '2026-04-20',
   '2026-04-20',
   '2026-04-20',
   '2026-04-20',
   '2026-04-20',
   '2026-04-20',
   '2026-04-20',
   '2026-04-20',
   '2026-04-16',
   '2026-04-14',
   '2026-04-14',
   '2026-04-13'],
  ['2026-05-12',
   '2026-05-12',
   '2026-05-08',
   '2026-05-08',
   '2026-05-08',
   '2026-05-08',
   '2026-05-07',
   '2026-05-06',
   '2026-05-04',
   '2026-05-04',
   '2026-04-23',
   '2026-04-23',
   '2026-05-04',
   '2026-05-04',
   '2026-04-23',
   '2026-04-23',
   '2026-04-30',
   '2026-04-28',
   '2026-04-28',
   '2026-04-27']]]

In [414]:
df_vurn = pd.DataFrame({
    "vendor_product": teaser__meta_list,
    "cve_id": teaser__title_list,
    "vulnerability_name": teaser__vuln_name,
    "description": teaser__vuln_name_value,
    "cwe_link": realted_cwe_link,
    "cwe_id": related_cwe,
    "ransomware": ransomware_campaigns,
    "action": action_list,
    "date_added": Added_date_list,
    "due_date": Due_date_list
})

In [418]:
df_vurn

,vendor_product,cve_id,vulnerability_name,description,cwe_link,cwe_id,ransomware,action,date_added,due_date
0,Microsoft | Windows,CVE-2026-32202,Microsoft Windows Protection Mechanism Failure...,Microsoft Windows Shell contains a protection ...,https://cwe.mitre.org/data/definitions/693,CWE-693,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-28,2026-05-12
1,ConnectWise | ScreenConnect,CVE-2024-1708,ConnectWise ScreenConnect Path Traversal Vulne...,ConnectWise ScreenConnect contains a path trav...,https://cwe.mitre.org/data/definitions/22,CWE-22,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-28,2026-05-12
2,SimpleHelp | SimpleHelp,CVE-2024-57726,SimpleHelp Missing Authorization Vulnerability:,SimpleHelp contains a missing authorization vu...,https://cwe.mitre.org/data/definitions/862,CWE-862,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-24,2026-05-08
3,SimpleHelp | SimpleHelp,CVE-2024-57728,SimpleHelp Path Traversal Vulnerability:,SimpleHelp contains a path traversal vulnerabi...,https://cwe.mitre.org/data/definitions/22,CWE-22,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-24,2026-05-08
4,Samsung | MagicINFO 9 Server,CVE-2024-7399,Samsung MagicINFO 9 Server Path Traversal Vuln...,Samsung MagicINFO 9 Server contains a path tra...,https://cwe.mitre.org/data/definitions/22,CWE-22,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-24,2026-05-08
5,D-Link | DIR-823X,CVE-2025-29635,D-Link DIR-823X Command Injection Vulnerability:,D-Link DIR-823X contains a command injection v...,https://cwe.mitre.org/data/definitions/77,CWE-77,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-24,2026-05-08
6,Marimo | Marimo,CVE-2026-39987,Marimo Remote Code Execution Vulnerability:,Marimo contains an pre-authorization remote co...,https://cwe.mitre.org/data/definitions/306,CWE-306,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-23,2026-05-07
7,Microsoft | Defender,CVE-2026-33825,Microsoft Defender Insufficient Granularity of...,Microsoft Defender contains an insufficient gr...,https://cwe.mitre.org/data/definitions/1220,CWE-1220,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-22,2026-05-06
8,JetBrains | TeamCity,CVE-2024-27199,JetBrains TeamCity Relative Path Traversal Vul...,JetBrains TeamCity contains a relative path tr...,https://cwe.mitre.org/data/definitions/23,CWE-23,Known,"Apply mitigations per vendor instructions, fol...",2026-04-20,2026-05-04
9,Quest | KACE Systems Management Appliance (SMA),CVE-2025-32975,Quest KACE Systems Management Appliance (SMA) ...,Quest KACE Systems Management Appliance (SMA) ...,https://cwe.mitre.org/data/definitions/287,CWE-287,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-20,2026-05-04
10,Cisco | Catalyst SD-WAN Manager,CVE-2026-20128,Cisco Catalyst SD-WAN Manager Storing Password...,Cisco Catalyst SD-WAN Manager contains a stori...,https://cwe.mitre.org/data/definitions/257,CWE-257,Unknown,Please adhere to CISA’s guidelines to assess e...,2026-04-20,2026-04-23
11,Synacor | Zimbra Collaboration Suite (ZCS),CVE-2025-48700,Synacor Zimbra Collaboration Suite (ZCS) Cross...,Synacor Zimbra Collaboration Suite (ZCS) conta...,https://cwe.mitre.org/data/definitions/79,CWE-79,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-20,2026-04-23
12,PaperCut | NG/MF,CVE-2023-27351,PaperCut NG/MF Improper Authentication Vulnera...,PaperCut NG/MF contains an improper authentica...,https://cwe.mitre.org/data/definitions/287,CWE-287,Known,"Apply mitigations per vendor instructions, fol...",2026-04-20,2026-05-04
13,Kentico | Kentico Xperience,CVE-2025-2749,Kentico Xperience Path Traversal Vulnerability:,Kentico Xperience contains a path traversal vu...,https://cwe.mitre.org/data/definitions/22,CWE-22,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-20,2026-05-04
14,Cisco | Catalyst SD-WAN Manager,CVE-2026-20133,Cisco Catalyst SD-WAN Manager Exposure of Sens...,Cisco Catalyst SD-WAN Manager contains an expo...,https://cwe.mitre.org/data/definitions/200,CWE-200,Unknown,Please adhere to CISA’s guidelines to assess e...,2026-04-20,2026-04-23
15,Cisco | Catalyst SD-WAN Manger,CVE-2026-20122,Cisco Catalyst SD-WAN Manager Incorrect Use of...,Cisco Catalyst SD-WAN Manager contains an inco...,https://cwe.mitre.org/data/definitions/648,CWE-648,Unknown,Please adhere to CISA’s guidelines to assess e...,2026-04-20,2026-04-23
16,Apache | ActiveMQ,CVE-2026-34197,Apache ActiveMQ Improper Input Validation Vuln...,Apache ActiveMQ contains an improper input val...,https://cwe.mitre.org/data/definitions/20,CWE-20,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-16,2026-04-30
17,Microsoft | SharePoint Server,CVE-2026-32201,Microsoft SharePoint Server Improper Input Val...,Microsoft SharePoint Server contains an improp...,https://cwe.mitre.org/data/definitions/20,CWE-20,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-14,2026-04-28
18,Microsoft | Office,CVE-2009-0238,Microsoft Office Remote Code Execution:,Microsoft Office Excel contains a remote code ...,https://cwe.mitre.org/data/definitions/94,CWE-94,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-14,2026-04-28
19,Adobe | Acrobat and Reader,CVE-2026-34621,Adobe Acrobat and Reader Prototype Pollution V...,Adobe Acrobat and Reader contain a prototype p...,https://cwe.mitre.org/data/definitions/1321,CWE-1321,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-13,2026-04-27

In [423]:
df_vurn['date_added'] = pd.to_datetime(df_vurn['date_added'])
df_vurn['due_date'] = pd.to_datetime(df_vurn['due_date'])

In [424]:
df_vurn.dtypes

vendor_product                   str
cve_id                           str
vulnerability_name               str
description                      str
cwe_link                         str
cwe_id                           str
ransomware                       str
action                           str
date_added            datetime64[us]
due_date              datetime64[us]
dtype: object

# Translate

In [443]:
translations = []

async with Translator() as translator:
    for text in df_vurn['description']:
        result = await translator.translate(text, dest='pl', src='en')
        translations.append(result.text)

df_vurn['description_PL'] = translations

In [444]:
df_vurn['description_PL'] = result.text

In [445]:
df_vurn

,vendor_product,cve_id,vulnerability_name,description,cwe_link,cwe_id,ransomware,action,date_added,due_date,description_PL
0,Microsoft | Windows,CVE-2026-32202,Microsoft Windows Protection Mechanism Failure...,Microsoft Windows Shell contains a protection ...,https://cwe.mitre.org/data/definitions/693,CWE-693,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-28,2026-05-12,Programy Adobe Acrobat i Reader zawierają prot...
1,ConnectWise | ScreenConnect,CVE-2024-1708,ConnectWise ScreenConnect Path Traversal Vulne...,ConnectWise ScreenConnect contains a path trav...,https://cwe.mitre.org/data/definitions/22,CWE-22,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-28,2026-05-12,Programy Adobe Acrobat i Reader zawierają prot...
2,SimpleHelp | SimpleHelp,CVE-2024-57726,SimpleHelp Missing Authorization Vulnerability:,SimpleHelp contains a missing authorization vu...,https://cwe.mitre.org/data/definitions/862,CWE-862,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-24,2026-05-08,Programy Adobe Acrobat i Reader zawierają prot...
3,SimpleHelp | SimpleHelp,CVE-2024-57728,SimpleHelp Path Traversal Vulnerability:,SimpleHelp contains a path traversal vulnerabi...,https://cwe.mitre.org/data/definitions/22,CWE-22,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-24,2026-05-08,Programy Adobe Acrobat i Reader zawierają prot...
4,Samsung | MagicINFO 9 Server,CVE-2024-7399,Samsung MagicINFO 9 Server Path Traversal Vuln...,Samsung MagicINFO 9 Server contains a path tra...,https://cwe.mitre.org/data/definitions/22,CWE-22,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-24,2026-05-08,Programy Adobe Acrobat i Reader zawierają prot...
5,D-Link | DIR-823X,CVE-2025-29635,D-Link DIR-823X Command Injection Vulnerability:,D-Link DIR-823X contains a command injection v...,https://cwe.mitre.org/data/definitions/77,CWE-77,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-24,2026-05-08,Programy Adobe Acrobat i Reader zawierają prot...
6,Marimo | Marimo,CVE-2026-39987,Marimo Remote Code Execution Vulnerability:,Marimo contains an pre-authorization remote co...,https://cwe.mitre.org/data/definitions/306,CWE-306,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-23,2026-05-07,Programy Adobe Acrobat i Reader zawierają prot...
7,Microsoft | Defender,CVE-2026-33825,Microsoft Defender Insufficient Granularity of...,Microsoft Defender contains an insufficient gr...,https://cwe.mitre.org/data/definitions/1220,CWE-1220,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-22,2026-05-06,Programy Adobe Acrobat i Reader zawierają prot...
8,JetBrains | TeamCity,CVE-2024-27199,JetBrains TeamCity Relative Path Traversal Vul...,JetBrains TeamCity contains a relative path tr...,https://cwe.mitre.org/data/definitions/23,CWE-23,Known,"Apply mitigations per vendor instructions, fol...",2026-04-20,2026-05-04,Programy Adobe Acrobat i Reader zawierają prot...
9,Quest | KACE Systems Management Appliance (SMA),CVE-2025-32975,Quest KACE Systems Management Appliance (SMA) ...,Quest KACE Systems Management Appliance (SMA) ...,https://cwe.mitre.org/data/definitions/287,CWE-287,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-20,2026-05-04,Programy Adobe Acrobat i Reader zawierają prot...
10,Cisco | Catalyst SD-WAN Manager,CVE-2026-20128,Cisco Catalyst SD-WAN Manager Storing Password...,Cisco Catalyst SD-WAN Manager contains a stori...,https://cwe.mitre.org/data/definitions/257,CWE-257,Unknown,Please adhere to CISA’s guidelines to assess e...,2026-04-20,2026-04-23,Programy Adobe Acrobat i Reader zawierają prot...
11,Synacor | Zimbra Collaboration Suite (ZCS),CVE-2025-48700,Synacor Zimbra Collaboration Suite (ZCS) Cross...,Synacor Zimbra Collaboration Suite (ZCS) conta...,https://cwe.mitre.org/data/definitions/79,CWE-79,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-20,2026-04-23,Programy Adobe Acrobat i Reader zawierają prot...
12,PaperCut | NG/MF,CVE-2023-27351,PaperCut NG/MF Improper Authentication Vulnera...,PaperCut NG/MF contains an improper authentica...,https://cwe.mitre.org/data/definitions/287,CWE-287,Known,"Apply mitigations per vendor instructions, fol...",2026-04-20,2026-05-04,Programy Adobe Acrobat i Reader zawierają prot...
13,Kentico | Kentico Xperience,CVE-2025-2749,Kentico Xperience Path Traversal Vulnerability:,Kentico Xperience contains a path traversal vu...,https://cwe.mitre.org/data/definitions/22,CWE-22,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-20,2026-05-04,Programy Adobe Acrobat i Reader zawierają prot...
14,Cisco | Catalyst SD-WAN Manager,CVE-2026-20133,Cisco Catalyst SD-WAN Manager Exposure of Sens...,Cisco Catalyst SD-WAN Manager contains an expo...,https://cwe.mitre.org/data/definitions/200,CWE-200,Unknown,Please adhere to CISA’s guidelines to assess e...,2026-04-20,2026-04-23,Programy Adobe Acrobat i Reader zawierają prot...
15,Cisco | Catalyst SD-WAN Manger,CVE-2026-20122,Cisco Catalyst SD-WAN Manager Incorrect Use of...,Cisco Catalyst SD-WAN Manager contains an inco...,https://cwe.mitre.org/data/definitions/648,CWE-648,Unknown,Please adhere to CISA’s guidelines to assess e...,2026-04-20,2026-04-23,Programy Adobe Acrobat i Reader zawierają prot...
16,Apache | ActiveMQ,CVE-2026-34197,Apache ActiveMQ Improper Input Validation Vuln...,Apache ActiveMQ contains an improper input val...,https://cwe.mitre.org/data/definitions/20,CWE-20,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-16,2026-04-30,Programy Adobe Acrobat i Reader zawierają prot...
17,Microsoft | SharePoint Server,CVE-2026-32201,Microsoft SharePoint Server Improper Input Val...,Microsoft SharePoint Server contains an improp...,https://cwe.mitre.org/data/definitions/20,CWE-20,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-14,2026-04-28,Programy Adobe Acrobat i Reader zawierają prot...
18,Microsoft | Office,CVE-2009-0238,Microsoft Office Remote Code Execution:,Microsoft Office Excel contains a remote code ...,https://cwe.mitre.org/data/definitions/94,CWE-94,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-14,2026-04-28,Programy Adobe Acrobat i Reader zawierają prot...
19,Adobe | Acrobat and Reader,CVE-2026-34621,Adobe Acrobat and Reader Prototype Pollution V...,Adobe Acrobat and Reader contain a prototype p...,https://cwe.mitre.org/data/definitions/1321,CWE-1321,Unknown,"Apply mitigations per vendor instructions, fol...",2026-04-13,2026-04-27,Programy Adobe Acrobat i Reader zawierają prot...

In [447]:
PATH = '/home/kacper/Dokumenty/vurn/'

In [ ]:
for i in range(80):
    sleep(3)
    response = requests.get(
        f'https://www.cisa.gov/known-exploited-vulnerabilities-catalog?page={i}',
        headers={"User-Agent": "szkolenie_uj/1.0"},
        timeout=10
    )
    print(f'Strona ({i+1}/80)')
    filepath = os.path.join(PATH, f'page{i}.html')

    with open(filepath, 'w', encoding='utf-8') as f:
              f.write(response.text)

Strona (1/80)
Strona (2/80)
Strona (3/80)
Strona (4/80)
Strona (5/80)
Strona (6/80)
Strona (7/80)
Strona (8/80)
Strona (9/80)
Strona (10/80)
Strona (11/80)
Strona (12/80)
Strona (13/80)
Strona (14/80)
Strona (15/80)
Strona (16/80)
Strona (17/80)
Strona (18/80)
Strona (19/80)
Strona (20/80)
Strona (21/80)
Strona (22/80)
Strona (23/80)
Strona (24/80)
Strona (25/80)
Strona (26/80)
Strona (27/80)
Strona (28/80)
Strona (29/80)
Strona (30/80)
Strona (31/80)
Strona (32/80)
Strona (33/80)
Strona (34/80)
Strona (35/80)
Strona (36/80)
Strona (37/80)
Strona (38/80)
Strona (39/80)
Strona (40/80)
Strona (41/80)
Strona (42/80)
Strona (43/80)
Strona (44/80)
Strona (45/80)
Strona (46/80)
Strona (47/80)
Strona (48/80)
Strona (49/80)
Strona (50/80)
Strona (51/80)
Strona (52/80)
Strona (53/80)
Strona (54/80)
Strona (55/80)
Strona (56/80)
Strona (57/80)
Strona (58/80)
Strona (59/80)
Strona (60/80)
Strona (61/80)
Strona (62/80)
Strona (63/80)
Strona (64/80)
Strona (65/80)
Strona (66/80)
Strona (67/80)
Strona (68/80)
Strona (69/80)
Strona (70/80)
Strona (71/80)
Strona (72/80)
Strona (73/80)
Strona (74/80)
Strona (75/80)
Strona (76/80)
Strona (77/80)
Strona (78/80)
Strona (79/80)

In [ ]:
print(response.status_code)